package com.atgx.ssm.dao;

import com.atgx.ssm.bean.DEPT;
import com.atgx.ssm.bean.DEPTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DEPTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    long countByExample(DEPTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int deleteByExample(DEPTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int insert(DEPT row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int insertSelective(DEPT row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    List<DEPT> selectByExample(DEPTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    DEPT selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int updateByExampleSelective(@Param("row") DEPT row, @Param("example") DEPTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int updateByExample(@Param("row") DEPT row, @Param("example") DEPTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int updateByPrimaryKeySelective(DEPT row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated Mon Apr 18 00:28:38 CST 2022
     */
    int updateByPrimaryKey(DEPT row);
}